version: '3'
services:

  web:
    container_name: web
    image: kwonjiyun/onezeromate-web
    expose:
      - 8080
    ports:
      - 8080:8080

      #redis:
      #image: kwonjiyun/redis
      #container_name: ubuntu-redis-1
      #hostname: ubuntu-redis-1
      #labels:
      # - "name=ubuntu-redis-1"
      #- "mode=standalone"
      #ports:
      #- 6379:6379
      #volumes:
      #- /config/redis.conf:/tmp/redis.conf
    #command: [ "redis-server", "/tmp/redis.conf" ]

  nginx:
    container_name: nginx
    image: kwonjiyun/onezeromate
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./spring:/usr/src/app
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro    # ssl 인증 시 접근 경로
      - ./certbot/conf/:/etc/nginx/ssl/    # ssl 인증서 생성 위치 (read-only option 제거)

    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_onezeromate
    #    command: certonly --webroot --webroot-path=/var/www/certbot --email ziyun1612@ewhain.net --agree-tos --no-eff-email -d onezeromate.com
    volumes:
      - ./certbot/www/:/var/www/certbot:rw   # ssl 인증 시 접근 경로
      - ./certbot/conf/:/etc/nginx/ssl/   # ssl 인증서 생성 위치 (변경)
      - ./certbot/log/:/var/log/letsencrypt:rw    # 로그 위치
    depends_on:
      - nginx
