version: '3'
services:

  web:
    container_name: web
    image: kwonjiyun/onezeromate-web
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: kwonjiyun/redis

  nginx:
    container_name: nginx
    image: kwonjiyun/onezeromate
    ports:
      - 80:80
    depends_on:
      - web