version: '3'
services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: /srv/ubuntu/Dockerfile
    command: java -jar -Dspring.profiles.active=prod app.jar
    expose:
      - 8080
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web